config/routes.rb
Rails.application.routes.draw do
  mount ReactiveRecord::Engine => "/rr"
  devise_for :users
  root to: 'pages#home'
  resources :conversations, only: :index
end

app/models/_react_public_models.rb
# app/models/_react_public_models.rb
require_tree './public'

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :user1, class_name: "User"
  belongs_to :user2, class_name: "User"
  has_many :messages

  def users
    return [user1, user2]
  end

  def other_user(user)
    users.include?(user) ? (users - [user]).first : nil
  end

  def unread_messages(user)
    messages.where(user: other_user(user), read_at: nil)
  end

  def unread_messages_count(user)
    unread_messages(user).count
  end

  def unread_messages?(user)
    unread_messages_count(user) > 0
  end

  def last_message
    messages.order(created_at: :asc).last
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :conversation

  validates :content, presence: true
  validates :conversation, presence: true
  validates :user, inclusion: { in: :users }

  def mark_as_read
    self.read_at = DateTime.now
    self.save
  end

  def users
    conversation.users
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :messages

  def conversations
    Conversation.includes(:messages)
                .where("user1_id = :id OR user2_id = :id", id: id)
                .order("messages.created_at DESC")
  end

  def other_user(conversation)
    conversation.users.include?(self) ? conversation.other_user(self) : nil
  end

  def unread_conversations
    conversations.select { |c| c.unread_messages?(self) }
  end

  def unread_conversations_count
    unread_conversations.count
  end

  def unread_conversations?
    unread_conversations_count > 0
  end

  def one_avatar_url
    avatar_url ? avatar_url : "http://placehold.it/64x64"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    @conversations = current_user.conversations
    if params[:conversation_id]
      @selected_conversation = @conversations.find(params[:conversation_id])
    else
      @selected_conversation = @conversations.first
    end
    @unread_messages = @selected_conversation.unread_messages(current_user)
    @unread_messages.each { |message| message.mark_as_read }
    @unread_conversations_count = current_user.unread_conversations_count
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/index.html.erb
<%= content_for :title do %>
  <%= current_user.unread_conversations_count > 0 ? "(#{@unread_conversations_count}) Inbox" : "Inbox" %>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-4" id="conversation-list">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4>Inbox</h4>
        </div>
        <div class="panel-body fixed-height">
          <div class="flexbox-columns-start">
            <% @conversations.each do |conversation| %>
              <div class="conversation-link flexbox-start">
                <span class="flex-item-shrink"><%= image_tag conversation.other_user(current_user).one_avatar_url, class: "avatar-square" %></span>
                <div class="conversation-preview flexbox-columns flex-item">
                  <ul class="conversation-header list-unstyled list-inline flex-item">
                    <li><h6><%= conversation.other_user(current_user).first_name %></h6></li>
                    <li class="date"><%= conversation.last_message.created_at.strftime("%b %e") %></li>
                  </ul>
                  <div class="message-preview flex-item">
                    <span><%= conversation.last_message.content %></span>
                  </div>
                </div>
              </div>
            <% end %>
            <div class="end-of-messages">
              <p>End of messages</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-8" id="message-list">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4><%= @selected_conversation.other_user(current_user).first_name %></h4>
        </div>
        <div class="panel-body fixed-height">
          <div id="wrapper">
            <div class="messages flexbox-columns-end flex-item">
              <% @selected_conversation.messages.order(created_at: :asc).each do |message| %>
                <div class="message-container flexbox-start flex-item">
                  <span class="flex-item-shrink"><%= image_tag message.user.one_avatar_url, class: "avatar-square-small" %></span>
                  <div class="message-content flex-item flexbox-columns">
                    <ul class="message-header list-unstyled list-inline flex-item">
                      <li><h6><%= message.user.first_name %></h6></li>
                      <li class="date"><%= message.created_at.strftime("%b %e, %l:%M%P") %></li>
                    </ul>
                    <%= simple_format message.content %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
          <div class="message-input" id="newMessage">
            <textarea id="newTextarea" placeholder="Answer here..."></textarea>
            <div class="actions flexbox hidden">
              <button class="btn btn-stop hidden">Cancel</button>
              <button class="btn btn-send hidden">Send</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<%= render 'shared/flashes' %>
<div class="navbar-wagon">
  <div class="container">
    <!-- Logo -->
    <%= link_to conversations_path, class: "navbar-wagon-brand" do %>
      <div class="badge-container">
        <i class="fa fa-envelope-o"></i>
        <% if user_signed_in? && current_user.unread_conversations? %>
          <div class="badge badge-blue"><%= @unread_conversations_count %></div>
        <% end %>
      </div>
    <% end %>

    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">
      <!-- Different navigation if login or not -->
      <% if user_signed_in? %>
        <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <% end %>
        <!-- Profile picture and dropdown -->
        <div class="">
          <div class="dropdown">
            <%= image_tag current_user.one_avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      <% else %>
        <!-- Login text link -->
        <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <% end %>
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>
      <!-- Button (call-to-action) -->
      <%# link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
    </div>

    <!-- Dropdown list appearing on mobile only -->
    <div class="hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <% if user_signed_in? %>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            <% else %>
              <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>